baseURL = "https://ken.cheo.dev"
languageCode = "en-us"
title = "kencx"
theme = "dark"
# enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", ":filename", ":fileModTime"]
  # lastmod = ["lastmod", ":git"]

[markup]
  [markup.highlight]
	lineNos = false
    lineNumbersInTable = false
	tabWidth = 4

  [markup.tableOfContents]
    endLevel = 5

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/posts/:title/"
  notes = "/:sections/:title/"
  projects = "/projects/:title/"
  books = "/books/:title/"

[params]
  author = "kencx"
  github = "https://github.com/kencx"
  email = "ken@cheo.dev"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 1

  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "notes/"
    weight     = 2

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight     = 3

  # [[menu.main]]
  #   identifier = "books"
  #   name       = "Books"
  #   url        = "books/"
  #   weight     = 4

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"
    weight     = 5
