baseURL = "https://ken.cheo.dev"
languageCode = "en-us"
title = "cheo.dev"
theme = "bamboo"
rssLimit = 20
copyright = "2021—{year}"
# enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", ":filename", ":fileModTime"]
  # lastmod = ["lastmod", ":git"]

[markup]
  [markup.highlight]
	lineNos = false
    lineNumbersInTable = false
	tabWidth = 4

  [markup.tableOfContents]
    endLevel = 5

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/posts/:title/"
  notes = "/:sections/:title/"
  projects = "/projects/:title/"

[params]
  author = "kencx"
  github = "https://github.com/kencx"
  email = "ken@cheo.dev"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 1

  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "notes/"
    weight     = 2

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"
    weight     = 3

[module]
  [[module.mounts]]
    source = "assets/covers"
    target = "static/covers"
  [[module.mounts]]
    source = "static"
    target = "static"
