[build]
  publish = "public"
  command = "hugo --gc --minify --enableGitInfo"

[build.environment]
  HUGO_VERSION = "0.112.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
	X-Frame-Options = "DENY"
	X-XSS-Protection = "1; mode=block"
	X-Content-Type-Options = "nosniff"
